### ISSUE TITLE
Right mouse click from Bluetooth mouse (possibly USB mouse too) not picked up

### ISSUE THREAD

**Issue by mjedrasik** [sfalexrog/openxcom-android#1] opened 2015-07-12 21:18 UTC
Hi,

Right mouse button doesn't work on Android (it goes "Back" or simulates escape, or exits back to launcher) when mouse is set to native mode in options, when using two button dedicated Bluetooth mouse with an Android device (test device 5.0.2 Samsung Galaxy Tab S 10,5" stock).

Got this link from @pelya who fixed his app rmb support recently.

Here's the commit if you'd like to see to trying make it work on openxcom:

https://github.com/pelya/commandergenius/commit/8a747fc9baa03c1bf8cf51310832dabbddcfb99a

Cheers

**Comment by sfalexrog** [comment] 2015-08-04 15:06
I've tried fixing it in @22fa3cd69, tested with a random Samsung device that I could lay my hands on for a couple of minutes. The device still vibrates as if a back button was pressed, and the middle mouse button still brings you home - I'm not sure there's a way around that, since apps shouldn't ever get the corresponding event.

For some reason dragging didn't work with extended mouse support, but that should be a separate issue. Basic mode seems to work just right for Samsungs.

Please do tell me your experience and whether we can close this issue!

**Comment by mjedrasik** [comment] 2015-08-04 16:40
Well the solution I chose was a move from stock Samsung rom to Cyanogenmod. 

Mouse works fine there so I ask you forgive me for not offering further assistance with this issue.

Good luck sorting it out though.

Best day,

**Comment by mjedrasik** [comment] 2015-08-04 16:41
Last time I used the stock rom with pelya's app I recall it worked fine though, so I reckon his solution is correct.

**Comment by sfalexrog** [comment] 2015-08-04 17:28
Well, since pelya is using SDL1.2 (or is it 1.3?), and we're on SDL2, the changes are somewhat different, but the idea is basically the same: to check if a "back" button was pressed on a mouse. From what I've gathered, Samsung is not the only manufacturer that maps mouse keys in weird ways, but so far they were the worst offenders in terms of edge case scenarios (i.e. if there's some device that behaves completely different to any other, it's definitely Samsung).

Curiously, I couldn't find a right-mouse-button bug in SDL2 bugtracker. I'm hesitant to file a bug and a patch myself having no simple way of reproducing it.

I'm going to close the issue for now, but feel free to re-open it in case there's something wrong with mice again!

**Closed as completed by sfalexrog** 2015-08-04 17:28 UTC

**Comment by LukasThyWalls** [comment] 2016-07-27 23:46
Hello.

Sorry if i am intruding in this old issue but i think it's related and only way to make my question.

I'm testing an old 10,1'' tablet (Android 4.0.3, old and cheap tablet, by the way) with a case with usb keyboard attached, and a usb mouse (in a usb hub). With some configuration (related with the keyboard layout) both devices worked without problems, and i tested too some apps, like Openxcom for Android.

In my case in openxcom with the mouse, the left button works like should be, the middle button do the same of left button, and right button do nothing. Testing in other apps, i see the left-middle button behaviour is the same too (the wheel works like should be), but in my case the right button open the apps menu, it doesn't make a "back button" click. But like i said, if i configured it in Openxcom to move the map or face the soldiers, do nothing.

Although the common use of an Android device is without a mouse, i think it should be great make it work because the port seems works flawlessly like the "PC" version with a mouse and a keyboard (key bindings included) and only felt missing the mouse right button to run like the main port. I tested too the touchscreen adaptations for the right click original behaviours (facing soldiers and moving map, mostly) and works with the touchscreen and with the mouse left button too.

I don't know if you have inquired about this and i can do some config to make the right button works, or give you some related information to research a solution in the future. I used a precompiled apk version of openxcom from this year, when i can i will edit this message with the commit code version, or add another with the required information.

Thanks in advance.
